# Generated by Django 4.2.1 on 2023-07-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartt',
        ),
    ]
